openapi: 3.0.3
info:
  title: API Test
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/status:
    get:
      summary: Statut
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string